### PR TITLE
Paul breaks all the things

### PR DESCRIPTION
**Pull request by plhnk**
- make sure your site is secure by using the latest versions of everything (probably requires you to delete your local node_modules folder and `npm install`)
- make styling stuff easier by using scoped sass 
- start componentization — `<Header>` and `<Illustration>` components now available

Hope this helps make things a little easier to edit!

### CODE REVIEW

**Comment by plhnk** [comment]
not sure why its breaking — says can't find gatsby-plugin-sass — but I'm able to build it...this might be a netlify issue, you could try re-starting the build

**Comment by victorvalle** [comment]
I'm afraid of breaking everything :S

**Comment by plhnk** [comment]
fear not Victor

**Comment by plhnk** [comment]
May-30-2020 13-39-30

**Comment by victorvalle** [comment]
Things to improve: calendar position in mobile viewport to relative + margin.
Still don't know how to remove the leaf breaks in mobile

**Comment by victorvalle** [comment]
Button does not link :(

**Comment by plhnk** [comment]
the button never linked??? you had it going to google

**Comment by victorvalle** [comment]
Thanks for cleaning up all the code :)
Also the animation effects now are much cool :)

Thanks @plhnk !

**Pull request merged**
